### ISSUE TITLE
getConfig() must be an instance of BaseObject, instance of stdClass returned.

### ISSUE THREAD

**Issue by nemorize** [rx-apps/member-title#1]
https://xetown.com/download/1707204#comment_1719938

관리자 화면에서 모듈을 설정하려 했으나..
아래 사진 처럼 오류가 발생하네요.
뭔 말이니 잘 몰라서....ㅜ
혹시 도움주신다면 감사하겠습니다.
도움을 못주셔도 감사합니다~~!!

![image](https://user-images.githubusercontent.com/51209191/202588614-c635565f-fbf0-4596-bcb4-36b57e8b45e3.png)

**Comment by nemorize** [comment]
PHP 7.0에서 리턴 타입 힌트로 object를 줄 수 없어 생긴 문제로 보입니다.
object 에서 stdClass 로 변경하여 7.0 에서도 정상 작동하나, 7.4 이상의 버전을 사용하는 것이 권장됩니다.

**Comment by leeseokhyun0912** [comment]
안녕하세요..
제가 깃허브는 처음이라 잘 몰라서 부족해도 양해 부탁드립니다...
업데이트를 해봤는데 이번에는 이런 오류가 뜨네요.ㅠ

![Screenshot 2022-11-18 at 20 22 02](https://user-images.githubusercontent.com/118532135/202694262-9d792828-2270-4f8c-834f-ac4764e5fb4d.JPG)

기존에 0.02 버전을 지우고 0.03 버전을 설치하니 대시보드에 이렇게 뜨네요.;;
![image](https://user-images.githubusercontent.com/118532135/202694894-29ec399b-0408-4f08-9fce-d14783c21f0e.png)


잘 몰라서 죄송합니다.ㅠ
열심히 공부해보겠습니다~!
시간내어 답변해주셔서 감사합니다~~!

**Comment by nemorize** [comment]
@leeseokhyun0912 
업로드 폴더명이 잘못되었습니다. `member-title` 이 아니라 `member_title` 입니다.

**Comment by leeseokhyun0912** [comment]
> @leeseokhyun0912 업로드 폴더명이 잘못되었습니다. `member-title` 이 아니라 `member_title` 입니다.

감사합니다..ㅠ
잘되네요~~~!!
감사합니다~~!

**Comment by parktaegang** [comment]
![image](https://user-images.githubusercontent.com/117503055/204075768-ae677922-ae66-48be-9498-cb918cbe883b.png)
회원 목록탭을 클릭하면 이런 애러가 뜹니다.

**Comment by nemorize** [comment]
@parktaegang 새 이슈로 다시 남겨주세요.
