### ISSUE TITLE
member_list.html 에서 stdClass를 배열로서 접근하는 문제

### ISSUE THREAD

**Issue by parktaegang** [rx-apps/member-title#2]
![image](https://user-images.githubusercontent.com/117503055/204115385-cabb06a4-2615-42ed-a90e-f7e609b0c96d.png)
안녕하세요.

다시 새로운 이슈로 등록 합니다.
회원 목록 탭을 클릭하면 이런 문구가 올라옵니다.

**Comment by nemorize** [comment]
회원가입 항목에서 전화번호를 사용하는 경우에 일어나는 문제입니다.

업데이트 이전에 수정하기를 원하신다면
아래 코드의 `$member['phone_number']` 를 `$member->phone_number` 로 변경하세요.

https://github.com/rx-apps/member-title/blob/2c97aa2472a219c6a466ab834d1240e6e029325f/tpl/member_list.html#L83

**Comment by parktaegang** [comment]
감사합니다!
