### ISSUE TITLE
php 7.4 회원목록 에러 뜹니다.

### ISSUE THREAD

**Issue by gaonnuris** [rx-apps/member-title#4]
7.4 버젼에서는
회원목록 누르면

Error #0 "Cannot use object of type stdClass as array" in modules/member_title/tpl/member_list.html on line 83
common/framework/debug.php:681

이렇게 에레메시지 뜹니다.

**Comment by nemorize** [comment]
커밋 https://github.com/rx-apps/member-title/commit/3d15154ef4c4f81df583a781671fe9f61f060481 에서 이미 수정되었습니다.
